### ISSUE TITLE
switch to atomist custom annotations

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist-skills/docker-file-policy#52]
<img width="1089" alt="Screen Shot 2021-05-25 at 3 17 42 pm" src="https://user-images.githubusercontent.com/1643888/119443805-11f61180-bcdf-11eb-9511-beea7f6b5851.png">

Reported that the link in the annotation does not point at the Dockerfile.  It points at some random file that was part of the commit change.

**Comment by slimslenderslacks** [comment]
https://github.com/actions/runner/issues/566

**Comment by slimslenderslacks** [comment]
https://github.com/actions/toolkit/issues/470

**Comment by cdupuis** [comment]
@slimslenderslacks the following structured link creates the embedded code block:

https://github.com/atomist-skills/docker-file-policy/blob/fd37109a84890c4e2185a5951ee7e0ea2f3a6109/deps.edn#L16-L19
