### ISSUE TITLE
Failed check although policy isn't configured to fail checks

### ISSUE THREAD

**Issue by cdupuis** [atomist-skills/docker-file-policy#91]
In T29E48P34 I've configured the `docker-file-policy` to not fail checks (see screenshot), yet I see https://github.com/atomist-skills/docker-vulnerability-scanner-skill/runs/3297623056

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/206707/129025189-ac6664fc-57c0-4328-ada5-585e237a3c35.png">

**Comment by slimslenderslacks** [comment]
I don't know what happened here but I can't reproduce this anymore.  Fail check is set to false on community so I'm going to monitor whether we see any failed checks in this team for a bit.
